name: Monitor WordPress Dependencies

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.2.0
      with:
        node-version: 16.x
    - uses: fabiankaegy/monitor-generated-wordpress-dependencies-action@main
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
